#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-widgetsnbextension
Version  : 4.0.9
Release  : 87
URL      : https://files.pythonhosted.org/packages/a1/e4/684abbfeb7a7a2e6a17aa8a5815e954a069edc0f567d912d2d3ffee800a9/widgetsnbextension-4.0.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/a1/e4/684abbfeb7a7a2e6a17aa8a5815e954a069edc0f567d912d2d3ffee800a9/widgetsnbextension-4.0.9.tar.gz
Summary  : Jupyter interactive widgets for Jupyter Notebook
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-widgetsnbextension-data = %{version}-%{release}
Requires: pypi-widgetsnbextension-license = %{version}-%{release}
Requires: pypi-widgetsnbextension-python = %{version}-%{release}
Requires: pypi-widgetsnbextension-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jupyter_packaging)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: change-widgetsnbextension-json-path.patch

%description
# Jupyter Widgets for Jupyter Notebook
![Version](https://img.shields.io/pypi/v/ipywidgets.svg?logo=pypi)](https://pypi.python.org/pypi/ipywidgets)

%package data
Summary: data components for the pypi-widgetsnbextension package.
Group: Data

%description data
data components for the pypi-widgetsnbextension package.


%package license
Summary: license components for the pypi-widgetsnbextension package.
Group: Default

%description license
license components for the pypi-widgetsnbextension package.


%package python
Summary: python components for the pypi-widgetsnbextension package.
Group: Default
Requires: pypi-widgetsnbextension-python3 = %{version}-%{release}

%description python
python components for the pypi-widgetsnbextension package.


%package python3
Summary: python3 components for the pypi-widgetsnbextension package.
Group: Default
Requires: python3-core
Provides: pypi(widgetsnbextension)

%description python3
python3 components for the pypi-widgetsnbextension package.


%prep
%setup -q -n widgetsnbextension-4.0.9
cd %{_builddir}/widgetsnbextension-4.0.9
%patch -P 1 -p1
pushd ..
cp -a widgetsnbextension-4.0.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694623131
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-widgetsnbextension
cp %{_builddir}/widgetsnbextension-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-widgetsnbextension/5dc7e0ef3878c3d4a92a7233208e6f91553de266 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/nbconfig/notebook.d/widgetsnbextension.json
/usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
/usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js.LICENSE.txt
/usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js.map

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-widgetsnbextension/5dc7e0ef3878c3d4a92a7233208e6f91553de266

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
