#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : widgetsnbextension
Version  : 3.1.3
Release  : 19
URL      : https://pypi.python.org/packages/95/da/6b87b2adf7c60a68cbeacb80bbc1346cf9235f31058d3c759fb18bb46c5f/widgetsnbextension-3.1.3.tar.gz
Source0  : https://pypi.python.org/packages/95/da/6b87b2adf7c60a68cbeacb80bbc1346cf9235f31058d3c759fb18bb46c5f/widgetsnbextension-3.1.3.tar.gz
Summary  : IPython HTML widgets for Jupyter
Group    : Development/Tools
License  : BSD-3-Clause
Requires: widgetsnbextension-config
Requires: widgetsnbextension-python3
Requires: widgetsnbextension-data
Requires: widgetsnbextension-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package config
Summary: config components for the widgetsnbextension package.
Group: Default

%description config
config components for the widgetsnbextension package.


%package data
Summary: data components for the widgetsnbextension package.
Group: Data

%description data
data components for the widgetsnbextension package.


%package python
Summary: python components for the widgetsnbextension package.
Group: Default
Requires: widgetsnbextension-python3

%description python
python components for the widgetsnbextension package.


%package python3
Summary: python3 components for the widgetsnbextension package.
Group: Default
Requires: python3-core

%description python3
python3 components for the widgetsnbextension package.


%prep
%setup -q -n widgetsnbextension-3.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517677559
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
%config /usr/etc/jupyter/nbconfig/notebook.d/widgetsnbextension.json

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
/usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js.map

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
